# Generated by Django 5.0.3 on 2024-05-04 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('agency', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=100)),
                ('link', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('salary', models.CharField(default='', max_length=50)),
                ('date_posted', models.CharField(default=django.utils.timezone.now, max_length=20)),
                ('seniority_level', models.CharField(default='', max_length=50)),
                ('employment_type', models.CharField(default='', max_length=50)),
                ('job_function', models.CharField(default='', max_length=255)),
                ('industries', models.CharField(default='', max_length=255)),
                ('state_code', models.CharField(blank=True, default='', max_length=2)),
                ('actual_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
