# Generated by Django 5.0.3 on 2024-04-14 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='industries',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='job_function',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='new_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority_level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
    ]
