# Generated by Django 5.0.3 on 2024-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='new_location',
        ),
        migrations.AddField(
            model_name='job',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
