# Generated by Django 5.0.3 on 2024-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_job_new_location_job_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
