# Generated by Django 5.0.3 on 2024-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_job_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
