# Generated by Django 5.0.3 on 2024-04-15 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='actual_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
