# Generated by Django 5.0.3 on 2024-04-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_job_actual_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='actual_date',
        ),
    ]
